---
deployment:
  tasks:
    - export DEPLOY_PATH=/home/username/yourdomain.com
    - /bin/cp -R * $DEPLOY_PATH
    - cd $DEPLOY_PATH
    - composer install --no-dev --optimize-autoloader
    - php artisan config:cache
    - php artisan route:cache
    - php artisan view:cache
